"""Markdown reporter: used for PR comments and quick terminal reading."""

from __future__ import annotations

from jinja2 import Environment

from ..report import Report
from ._common import build_context


def _oneline(value: object) -> str:
    """Collapse all whitespace (incl. newlines) to single spaces.

    Tool-controlled text rendered raw into Markdown could otherwise inject
    headings/list items or break out of the finding bullet on a newline.
    """
    return " ".join(str(value).split())


_ENV = Environment(trim_blocks=True, lstrip_blocks=True, autoescape=False)
_ENV.filters["oneline"] = _oneline

_TEMPLATE = _ENV.from_string(
    """# Security report: {{ repo_name }}

**Grade: {{ grade }} ({{ total }}/100)** · {{ grade_caption }}. Gate **{{ gate_status }}** (fails on: {{ fail_on }})

> A = strong, F = critical. The grade is the worst assessed domain.
{% if supply_chain %}

**Supply chain: {{ supply_chain.grade }} ({{ supply_chain.score }}/100)** · OpenSSF Scorecard posture (advisory, excluded from the grade)
{% endif %}

- Scanned: `{{ target }}`
- Generated: {{ generated_at }}
- Tools: {{ tools }}
{% if duplicates_removed %}
- Duplicates removed across tools: {{ duplicates_removed }}
{% endif %}

## Findings by severity

| Severity | Count |
|----------|-------|
{% for c in counts %}
| {{ c.emoji }} {{ c.label }} | {{ c.count }} |
{% endfor %}

{% if domains %}
## Score by domain

The grade is the worst assessed domain.

| Domain | Score | Findings |
|--------|-------|----------|
{% for d in domains %}
| {{ d.label }} | {{ d.score }}/100 | {{ d.findings }} |
{% endfor %}
{% if not_assessed %}

*Not assessed (no relevant files found): {{ not_assessed | join(', ') }}*
{% endif %}
{% endif %}

{% if groups %}
## Details
{% for g in groups %}

### {{ g.emoji }} {{ g.label }} ({{ g.findings|length }})
{% for f in g.findings %}
- **{{ f.rule_id | oneline }}** {{ f.title | oneline }}{% if f.file %} · `{{ f.file | oneline }}{% if f.line %}:{{ f.line }}{% endif %}`{% endif %}{% if f.resource %} _({{ f.resource | oneline }})_{% endif %}
{% if f.message %}
  - {{ f.message | oneline }}
{% endif %}
{% if f.remediation %}
  - 💡 {{ f.remediation | oneline }}
{% endif %}
{% if f.references %}
  - ref: {{ f.references[0] | oneline }}
{% endif %}
{% endfor %}
{% endfor %}
{% else %}
✅ No findings.
{% endif %}

---
*Generated by [repo-analyzer](https://github.com/TuroTheReal/repo-analyzer).*
"""
)


def render(report: Report) -> str:
    """Render the report as Markdown."""
    return _TEMPLATE.render(**build_context(report))
